<?php

//блок доставка
const DELIVERY_PRICE = 290;
const DELIVERY_TODAY_PRICE = 580;
const PRICE_TO_FREE_DELIVERY = 2000;
const DELIVERY_TIME = "3-7";
const DELIVERY_FITTING_PRICE = 350;
const PRICE_TO_FREE_DELIVERY_FITTING = 3001;
